layers:
  -
    name: Orth
    sub: City of the Great Pit
    world: LayerOne
    sections:
      -
        refTop: [0, 0, 0]
        refBottom: [-493, 16, 125]
        world: LayerOne
  -
    name: Edge of the Abyss
    sub: 0-1350 meters
    world: LayerOne
    effects:
      -
        name: DizzyAscensionEffect
        strength: 1
        durationRemaining: 15
    sections:
      -
        refTop: [2370, 236, 141]
        refBottom: [2500, 20, 123]
        world: LayerOne
      -
        refTop: [3908, 235, 107]
        refBottom: [3956, 24, -97]
        world: LayerOne
      -
        refTop: [5107, 239, -98]
        refBottom: [5149, 21, -99]
        world: LayerOne
  -
    name: Forest of Temptation
    sub: 1351-2600 meters
    world: LayerTwo
    sections:
      -
        refTop: [973, 236, -163]
        refBottom: [1673, 24, 19]
        world: LayerTwo
      -
        refTop: [385, 256, 14]
        refBottom: [0, 19, -149]
        world: LayerTwo
  -
    name: Great Fault
    sub: 2601-7000 meters
    world: LayerThree
    sections:
      -
        refTop: [0, 238, -149]
        refBottom: [0, 25, -149]
        world: LayerThree
      -
        refTop: [832, 232, -149]
        refBottom: [832, 25, -149]
        world: LayerThree
      -
        refTop: [1664, 232, -149]
        refBottom: [1664, 25, -149]
        world: LayerThree
      -
        refTop: [2496, 232, -149]
        refBottom: [2496, 25, -149]
        world: LayerThree
      -
        refTop: [3238, 232, -149]
        refBottom: [3238, 25, -149]
        world: LayerThree
      -
        refTop: [4160, 232, -149]
        refBottom: [4160, 25, -149]
        world: LayerThree
      -
        refTop: [4992, 232, -149]
        refBottom: [4992, 25, -149]
        world: LayerThree
  -
    name: Goblet of Giants
    sub: 7001-12000 meters
    world: LayerFour
    sections:
      -
        refTop: [0, 232, -148]
        refBottom: [74, 23, -538]
        world: LayerFour
      -
        refTop: [1498, 243, -442]
        refBottom: [1462, 21, -353]
        world: LayerFour
      -
        refTop: [2886, 241, -353]
        refBottom: [2859, 21, -276]
        world: LayerFour
      -
        refTop: [4145, 241, -260]
        refBottom: [0, 0, 0]
        world: LayerFour