#layers:
#  -
#    name: Edge of the Abyss
#    sub: 0-1350 meters
#    world: LayerOne
#    depth:
#      start: 0
#      end: 1350
#    effects:
#      -
#        name: PotionAscensionEffect
#        strength: 1
#        duration: 7
#        iterations: 3
#        effects:
#          - CONFUSION
#    # Fill this with the section names defined in the deeper world config
#    sections: [section1]
adventure-mode: false