[versions]
gearyPaper = "0.33.2"
guiy = "0.13.0"
deeperworld = "0.12.0"
chatty = "0.9.0"
packy = "0.8.7"


[libraries]
geary-papermc = { module = "com.mineinabyss:geary-papermc", version.ref = "gearyPaper" }
deeperworld = { module = "com.mineinabyss:deeperworld", version.ref = "deeperworld" }
guiy = { module = "com.mineinabyss:guiy-compose", version.ref = "guiy" }
chatty = { module = "com.mineinabyss:chatty-paper", version.ref = "chatty" }

packy = { module = "com.mineinabyss:packy", version.ref = "packy" }

minecraft-plugin-blocklocker = "nl.rutgerkok:blocklocker:1.13"
minecraft-plugin-hibiscuscommons = "me.lojosho:HibiscusCommons:0.6.3-d97e5686"
minecraft-plugin-hmccosmetics = "com.hibiscusmc:HMCCosmetics:2.7.8-e5fda588"
minecraft-plugin-discordsrv = "com.discordsrv:discordsrv:1.29.0"
minecraft-plugin-luckperms = "net.luckperms:api:5.4"
minecraft-plugin-placeholderapi = "me.clip:placeholderapi:2.11.6"
minecraft-plugin-mythichud = "io.lumine.mythichud:api:1.2.4-SNAPSHOT"
minecraft-plugin-bkcommonlib = "com.bergerkiller.bukkit:BKCommonLib:1.21.8-v1-SNAPSHOT"
minecraft-plugin-traincarts = "com.bergerkiller.bukkit:TrainCarts:1.21.8-v1-SNAPSHOT"
minecraft-plugin-tccoasters = "com.bergerkiller.bukkit:TCCoasters:1.21.5-v2-SNAPSHOT"
minecraft-plugin-shopkeepers = "com.nisovin.shopkeepers:ShopkeepersAPI:2.23.4"
