[versions]
gearyPaper = "0.31.27-dev.2"
guiy = "0.13.0-dev.3"
deeperworld = "0.11.9"
chatty = "0.8.10"
eternalfortune = "0.4-SNAPSHOT"
packy = "0.7.3"
blocky = "0.10.15"


[libraries]
geary-papermc = { module = "com.mineinabyss:geary-papermc", version.ref = "gearyPaper" }
deeperworld = { module = "com.mineinabyss:deeperworld", version.ref = "deeperworld" }
guiy = { module = "com.mineinabyss:guiy-compose", version.ref = "guiy" }
chatty = { module = "com.mineinabyss:chatty-paper", version.ref = "chatty" }

eternalfortune = { module = "com.mineinabyss:eternalfortune", version.ref = "eternalfortune" }
packy = { module = "com.mineinabyss:packy", version.ref = "packy" }
blocky = { module = "com.mineinabyss:blocky", version.ref = "blocky" }

minecraft-plugin-blocklocker = "nl.rutgerkok:blocklocker:1.12.2"
minecraft-plugin-hibiscuscommons = "me.lojosho:HibiscusCommons:0.4.7"
minecraft-plugin-hmccosmetics = "com.hibiscusmc:HMCCosmetics:2.7.3"
minecraft-plugin-discordsrv = "com.discordsrv:discordsrv:1.28.0"
minecraft-plugin-luckperms = "net.luckperms:api:5.4"
minecraft-plugin-placeholderapi = "me.clip:placeholderapi:2.11.6"
minecraft-plugin-mythichud = "io.lumine.mythichud:api:1.1.0-SNAPSHOT"
minecraft-plugin-bkcommonlib = "com.bergerkiller.bukkit:BKCommonLib:1.21-v1-SNAPSHOT"
minecraft-plugin-traincarts = "com.bergerkiller.bukkit:TrainCarts:1.21-v1-SNAPSHOT"
minecraft-plugin-tccoasters = "com.bergerkiller.bukkit:TCCoasters:1.21-v1-SNAPSHOT"
