[versions]
geary = "0.19.113"
gearyaddons = "0.7.45"
looty = "0.8.66"
guiy="0.7.25"
deeperworld="0.6.82"
chatty="0.3.53"
mobzy="0.18.84"
protocolburrito = "0.5.37"


[libraries]
protocolburrito = { module = "com.mineinabyss:protocolburrito", version.ref = "protocolburrito" }
geary-papermc-core = { module = "com.mineinabyss:geary-papermc-core", version.ref = "geary" }
geary-commons-papermc = { module = "com.mineinabyss:geary-commons-papermc", version.ref = "gearyaddons" }
looty = { module = "com.mineinabyss:looty", version.ref = "looty" }
deeperworld = { module = "com.mineinabyss:deeperworld", version.ref = "deeperworld" }
guiy = { module = "com.mineinabyss:guiy-compose", version.ref = "guiy" }
chatty = { module = "com.mineinabyss:chatty-paper", version.ref = "chatty" }
mobzy = { module = "com.mineinabyss:mobzy", version.ref = "mobzy" }

minecraft-plugin-blocklocker = "nl.rutgerkok:blocklocker:1.10.4-SNAPSHOT"
minecraft-plugin-gsit = "com.gecolay:gsit:1.2.2"
minecraft-plugin-mccosmetics = "io.lumine:MCCosmetics-Dist:1.0.0-SNAPSHOT"
minecraft-plugin-hmccosmetics = "com.hibiscus:hmccosmetics:1.11.2"
minecraft-plugin-discordsrv = "com.discordsrv:discordsrv:1.25.1"
minecraft-plugin-luckperms = "net.luckperms:api:5.4"
minecraft-plugin-modelengine = "com.ticxo.modelengine:api:R2.5.0"
